- name: Include vars
  include_vars: trustgrid.yml

- name: Get package url
  shell:
    cmd: |
      if [ "{{ ccf_ver }}" = "latest" ]; then
        curl -s {{ ccf_releases_base_url }}/latest | egrep 'https://.*\.deb' | cut -d\" -f4
      else
        echo "{{ ccf_releases_base_url }}/{{ ccf_suffix }}/ccf_{{ ccf_ver }}_amd64.deb"
      fi
  register: ccf_deb_url

- name: Install CCF
  apt:
    deb: "{{ ccf_deb_url.stdout }}"
  become: yes

- name: Copy cchost
  copy:
    src: "/opt/ccf-{{ ccf_ver }}/bin/cchost"
    dest: "/usr/bin/cchost"
    remote_src: true
    mode: a=rx
  become: true
  when: run_only|bool

- name: Remove release
  apt:
    name: ccf
    state: absent
  become: true
  when: run_only|bool
